<a href="https://colab.research.google.com/github/subhamghimire/Machine-Learning/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [0]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [0]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
np.linspace(0,10,2)

array([ 0., 10.])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.random.rand(5)

array([0.94261634, 0.61293512, 0.69517131, 0.89059599, 0.48302088])

In [0]:
np.random.rand(5,5)

array([[0.11113167, 0.86029046, 0.99396086, 0.04678947, 0.12242387],
       [0.87332068, 0.50305962, 0.08971579, 0.98720079, 0.26215925],
       [0.2101295 , 0.14860002, 0.10167325, 0.51105885, 0.1990298 ],
       [0.54687115, 0.46568483, 0.16082899, 0.45996758, 0.82607275],
       [0.74890807, 0.57530928, 0.09743096, 0.84572653, 0.87374073]])

In [0]:
np.random.randn(4,4)

array([[-0.33898597, -0.24216166, -0.09140442, -0.0340771 ],
       [ 0.26409356,  0.96079042,  0.45822944,  0.14391625],
       [-1.44295916, -0.83017336, -0.86109703, -1.58070263],
       [-0.18579543, -0.05813349,  0.58819622,  1.33427507]])

In [0]:
np.random.randint(1,50,10)

array([49, 18, 38, 32,  6, 17, 42,  7, 48, 41])

In [0]:
np.random.random(5)

array([0.41032586, 0.54627318, 0.24177089, 0.05258173, 0.30228847])

In [0]:
np.random.random([5])*4 -2

array([-0.50944278,  0.99190457, -1.83563271, -1.05841099,  1.39884016])

In [0]:
 arr = [1,2,3,4,5]
 arr



[1, 2, 3, 4, 5]

In [0]:
arr = np.arange(9)

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
arr = np.random.randint(0,20,8)
arr

array([11,  3,  8,  6, 17,  5, 10,  3])

In [0]:
arr.max()

17

In [0]:
arr.argmax()

4

In [0]:
arr.argmin()

1

In [0]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[5]

5

In [0]:
arr[0:3]

array([0, 1, 2])

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[:4] = 50
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [0]:
arr_2d[1,0]

20

In [0]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [0]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [0]:
 arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr[arr>5]

array([50, 50, 50, 50,  6,  7,  8,  9, 10])

In [0]:
arr_2d = np.arange(20).reshape(4,5)
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
arr_2d[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [0]:
arr

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr + arr

array([100, 100, 100, 100,   8,  10,  12,  14,  16,  18,  20])

In [0]:
np.exp(arr)

array([5.18470553e+21, 5.18470553e+21, 5.18470553e+21, 5.18470553e+21,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [0]:
np.sqrt(arr)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [0]:
arr


array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [0]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [0]:
arr[arr%2==0]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [0]:
arr = np.arange(0,9)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [0]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [0]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
np.random.rand(1)

array([0.38272619])

In [0]:
np.random.randn(25)

array([ 0.59859159,  1.52844087, -0.91270746,  1.26252439,  0.45018188,
       -0.17826038,  0.37323061, -1.36833964,  0.59457395, -0.3634238 ,
       -0.28297741,  0.13918815, -0.71840142, -1.1910986 ,  1.06949009,
       -1.44963559,  1.53624519, -2.15264804, -0.47213926,  1.01349549,
        0.1917817 ,  1.82248178,  0.54894558,  1.38022392,  0.37626477])

In [0]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [0]:
np.linspace(0,1,num=20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [0]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
arr[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
arr[3,4]

20

In [0]:
arr[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [0]:
arr[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
arr.sum()

325

In [0]:
arr.std()

7.211102550927978

In [0]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])